name: Deploy main branch & test builds

on:
  push:
    branches: [main, ci]

jobs:
  deploy:
    name: Deploy master tag image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip') && !contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:master .
      - name: Push master tag to ghcr.io
        run: docker push ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:master

  build-projects:
    name: Run sample commands in master tag image
    needs: deploy
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:master
    steps:
      - run: uname -a
      - run: lsb_release -a
