name: Deploy main branch & test builds

on:
  push:
    branches: [main, ci]

jobs:
  deploy:
    name: Deploy master tag image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip') && !contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:master .
      - name: Tag same image with date
        run: docker tag ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:master ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:${{ steps.date.outputs.date }}
      - name: Push master tag to ghcr.io
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:${{ steps.date.outputs.date }}
          docker push ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:master

  # This check is not valid, will probably delete soon
  check-autologin:
    name: Run bash sample commands in master tag image
    needs: deploy
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:master
      options: "--entrypoint /entrypoint.sh"
    steps:
      - run: uname -a

  check-ssh:
    name: Run SSH sample commands in master tag image
    needs: deploy
    runs-on: ubuntu-latest
    services:
      rpios:
        image: ghcr.io/${{ github.repository_owner }}/qemu-rpi-os-lite:master
        ports:
          - 5022:5022
    steps:
      - name: Give 2m30s for the docker image to start up QEMU and Raspberry Pi OS
        run: sleep 150
      - name: Executing remote ssh command 1
        uses: appleboy/ssh-action@master
        with:
          host: rpios
          username: pi
          password: raspberry
          port:  ${{ job.services.rpios.ports[5022] }}
          # QEMU might still take some extra time to start up Raspberry Pi OS
          timeout: 5m
          script: |
            uname -a
            cat /etc/os-release
            touch my_file.txt
      - name: Executing remote ssh command 2
        uses: appleboy/ssh-action@master
        with:
          host: rpios
          username: pi
          password: raspberry
          port:  ${{ job.services.rpios.ports[5022] }}
          script: |
            uname -a
            cat /etc/os-release
            ls
